import React from 'react';
import { Link } from '../api/sdk.js';
import Header from '../components/Header.jsx';

const m1 = [
  { icon:'\u{1F697}', title:'Driver Supply First', side:'Driver', kpi:'500 active drivers before soft launch day', items:['Target 500+ active drivers in DFW before going public \u2014 no marketplace launches with empty supply','Post aggressively on Indeed, ZipRecruiter, iHire Transportation, Snagajob with "earn 60% more than Uber" headline','Infiltrate Uberpeople.net & rideshare Facebook groups \u2014 existing frustrated Uber/Lyft drivers are your #1 source','Offer first 500 drivers a 3-month platform fee waiver \u2014 removes all friction to signing up','Partner with Platinum Drivers & TransForce for pre-vetted driver pipelines'] },
  { icon:'\u{1F91D}', title:'Community & Diaspora Seeding', side:'Both', kpi:'25K downloads from community channels alone', items:['Partner with temples, mosques, and South Asian community centers in DFW \u2014 host information events','Tamil FM & Telugu FM paid radio spots in DFW \u2014 reach 50K+ diaspora listeners directly','Create WhatsApp broadcast groups seeded with 20\u201330 community leaders per group who push downloads organically','Hire 15\u201320 Student Brand Ambassadors at UT Dallas, SMU, TCU, UTA, and UNT \u2014 each brings 200+ contacts','Offer riders first 3 rides free with ambassador referral code to guarantee first 10K installs'] },
  { icon:'\u{1F4F1}', title:'Organic Social Launch Blitz', side:'Both', kpi:'500K organic reach in Month 1', items:['Launch on all 10 organic channels simultaneously on Day 1 \u2014 Instagram, TikTok, YouTube, LinkedIn, Facebook, X, Threads, Reddit, Pinterest, Quora','Post a viral "Why we quit Uber" founder story \u2014 JP\'s personal driving experience is the hook','Create a TikTok series: "Driver vs Uber: Same trip, real earnings comparison" \u2014 raw, relatable, shareable','Run a Reddit AMA in r/uberdrivers and r/ridesharetips as JP \u2014 drive both driver & rider awareness','Publish a Medium blog post on the rideshare exploitation problem \u2014 seed on LinkedIn for viral reach'] },
  { icon:'\u{1F504}', title:'Referral Program Activation', side:'Both', kpi:'30% of downloads via referral by end of Month 1', items:['Launch Referral Hero \u2014 rider gets $5 credit, friend gets first 2 rides free. Simple, shareable, instant','Driver referral: bring a driver friend \u2192 earn $50 bonus after their 10th ride. Drivers have big networks','Use ManyChat on Instagram & Facebook to automate referral link delivery via DM','Add in-app share intent after every completed ride \u2014 prompt with "Loved it? Share AYRO & get $5"','Track referral loops with Serenities AI dashboard \u2014 optimize top-performing referrer profiles weekly'] },
  { icon:'\u{1F4E6}', title:'ASO (App Store Optimization)', side:'Both', kpi:'Top 10 ranking for "rideshare app" in DFW searches', items:['Keyword Targeting: Partner with Sem Nexus for full ASO audit. Target: "rideshare app", "cheap uber alternative", "driver app earnings", "no surge pricing"','Visual Assets: Draftss to create A/B tested screenshots, preview videos, and app icon variants. Test 3 versions','Review Strategy: Prompt every driver and rider for a 5-star review after their 3rd completed interaction. Target 500+ reviews by end of Month 1'] },
];
const m2 = [
  { icon:'\u{1F4B8}', title:'Paid Digital Ads Blitz', side:'Paid', kpi:'$1.50\u2013$2.50 CPI across paid channels', items:['Google UAC \u2014 target "Uber alternative", "cheap rideshare", "driver jobs Dallas" keywords. Budget: 35% of ad spend','Facebook & Instagram app install campaigns \u2014 lookalike audiences of South Asian, driver community demographics. Budget: 25%','TikTok app install ads using organic viral content as paid \u2014 "same trip, driver earns 60% more" creative. Budget: 15%','YouTube pre-roll ads targeting rideshare, driver, transportation channels \u2014 15-second non-skippable format','Snapchat & Reddit ads targeting 18\u201335 urban demographics in target cities','Spotify Ads \u2014 audio ads during commute hours: "Your Uber is costing you $12 more than it should"'] },
  { icon:'\u{1F4CD}', title:'Geofencing \u2014 High-Density Zones', side:'Rider', kpi:'50K downloads from geofencing + hyperlocal', items:['GroundTruth & GeoFence Pro \u2014 target within 1-mile radius of DFW International Airport','Geofence major hotels, Airbnbs, and tourist zones in DFW \u2014 serve AYRO ads to phones entering these locations','Target stadiums and concert venues on event days \u2014 when surge pricing hits, AYRO\'s fixed price ad appears','Nextdoor ads in high-density neighborhoods \u2014 position as the "neighborhood-friendly rideshare"','Vibe (Roku TV) \u2014 connected TV ads in evenings when families plan weekend rides'] },
  { icon:'\u{1F3A4}', title:'Influencer Marketing Push', side:'Both', kpi:'80K downloads attributed to influencer channels', items:['Partner with The Rideshare Guy, Rideshare Professor, and Your Driver Mike \u2014 combined audience of 500K+ gig economy followers','Micro-influencers in DFW: 10\u201320 creators with 10K\u2013100K followers in transportation, finance, or diaspora niches','Hookpoint to produce 3\u20135 viral short-form videos showing real driver earnings comparisons \u2014 authentic UGC-style','Sponsor The Rideshare Hub podcast episode \u2014 high-intent driver audience actively looking for better options','Give top influencers custom referral codes trackable through Referral Hero \u2014 pay per verified install'] },
  { icon:'\u{1F4F0}', title:'Press, PR & Media Coverage', side:'Both', kpi:'5+ media placements generating 1M+ impressions', items:['Distribute launch press release via EIN Presswire & eReleases \u2014 target tech, startup, and transportation beats','Pitch Press Ranger contacts at Dallas Morning News, Fort Worth Star-Telegram, and local TV news','Submit to TechCrunch, The Information, Business Insider with JP\'s founder story angle','Use Audiogo radio for 30-second spots on local AM/FM stations during morning commute (6\u20139am)','Pitch App Store / Google Play featured placement \u2014 contact category manager 3 weeks before peak coverage'] },
  { icon:'\u{1F4E7}', title:'Email, SMS & CRM Activation', side:'Both', kpi:'40%+ open rate on SMS, 25%+ on email', items:['Zoho Campaigns \u2014 3-email drip sequence to all Month 1 signups: welcome \u2192 first ride offer \u2192 refer a friend bonus','SMS marketing via Zoho to driver waitlist: "AYRO is live in your city \u2014 start earning this week"','Instantly.ai for cold email outreach to corporate contacts \u2014 "AYRO for Business: Fixed-price employee rides"','Re-engage Month 1 riders who haven\'t taken a second ride with a $3 credit push via SMS and email'] },
  { icon:'\u{1F3D9}', title:'City Expansion Strategy', side:'Both', kpi:'DFW + 2 cities active by end of Month 2', items:['Expand to 2\u20133 additional Texas metros: Houston and San Antonio \u2014 each new market = new press hook','Replicate the driver-first seeding model in each new market before going live to riders','Run city-specific launch events partnered with community organizations \u2014 drives local earned media','Target Indian diaspora populations in DFW and Houston \u2014 massive organic driver and rider pool'] },
];
const m3 = [
  { icon:'\u{1F504}', title:'Referral Orbit \u2014 Full Power', side:'Both', kpi:'200K downloads from referral alone', items:['By Month 3, 400K existing users are the biggest marketing channel \u2014 each referring 1.25 people = 500K new downloads','Launch "AYRO Champion" program \u2014 top 100 referrers get permanent free rides, merchandise, or monthly cash rewards','Time a "Refer 3 Friends Week" campaign with 3x referral bonuses \u2014 creates urgency and viral spikes','Driver referral bonus increases to $100 per driver referred in Month 3 \u2014 drivers become unpaid sales force'] },
  { icon:'\u{1F3AF}', title:'Strategic Partnerships', side:'Both', kpi:'100K downloads from B2B channels', items:['Corporate accounts: Offer "AYRO for Business" with bulk rides for employees \u2014 HR contacts at 500+ DFW companies','University partnerships: UT Dallas, SMU, TCU, UTA, UNT \u2014 student ridership programs with campus ambassadors','Hotel & Airbnb partnerships: Partner with 100+ properties for guest transportation','Event partnerships: Dallas Stars, Mavericks, concert venues \u2014 official ride partner deals'] },
  { icon:'\u{1F4CA}', title:'Retention & Re-engagement', side:'Both', kpi:'60% Day-30 retention', items:['Launch "AYRO Gold" loyalty program \u2014 points for rides, redeemable for free rides','SMS win-back campaigns for users inactive 14+ days','Push notification personalization based on ride patterns','In-app challenges: "Take 5 rides this week" \u2014 reward with $5 credit'] },
  { icon:'\u{1F680}', title:'Viral Power Plays', side:'Both', kpi:'1 viral moment generating 500K+ impressions', items:['Free Ride Weekend: up to $15 per ride, Friday\u2013Sunday. Creates massive download spike','"Quit Uber" TikTok Challenge: drivers film switching from Uber to AYRO showing earnings difference. #QuitUber','Driver Milestone Campaign: Celebrate "1,000th AYRO Driver" and "100,000th AYRO Rider" \u2014 press release, social blast'] },
];

const Section = ({items, color}) => items.map((s,i) => (
  <div key={i} className="rounded-xl p-5 bg-white border border-gray-200 mb-5" style={{boxShadow:'0 2px 8px rgba(0,0,0,0.06)'}}>
    <div className="flex items-center gap-2.5 mb-2"><span className="text-xl">{s.icon}</span><span className="text-gray-900 font-bold text-base">{s.title}</span><span className="text-xs px-2.5 py-1 rounded-md bg-gray-100 text-gray-500 ml-auto border border-gray-200">{s.side}</span></div>
    <div className="space-y-2 my-3">{s.items.map((item,j)=><div key={j} className="flex gap-2 text-base text-gray-600 leading-relaxed"><span className="text-gray-300 mt-0.5 flex-shrink-0">&rsaquo;</span><span>{item}</span></div>)}</div>
    <div className="text-sm pt-3 border-t border-gray-100"><span className="text-gray-400">KPI: </span><span className="font-semibold" style={{color}}>{s.kpi}</span></div>
  </div>
));

export default function Page() {
  return (
    <div className="min-h-screen bg-white">
      <Header />
      <div className="max-w-4xl mx-auto p-6 pt-40">
        <div className="text-center mb-8">
          <h2 className="text-3xl font-extrabold text-gray-900 mb-2">1 Million Downloads in 90 Days</h2>
          <p className="text-gray-500 text-base">From Soft Launch to Full Launch &mdash; a month-by-month playbook.</p>
        </div>
        <div className="grid grid-cols-4 gap-4 mb-10">{[{
'n':'100K',l:'Month 1 Target',c:'#f97316'},{n:'400K',l:'Month 2 Target',c:'#423DF9'},{n:'500K',l:'Month 3 Target',c:'#0e7a50'},{n:'1M+',l:'Total Downloads',c:'#0b1a30'}].map((s,i)=>(<div key={i} className="rounded-xl p-4 text-center bg-white border border-gray-200" style={{boxShadow:'0 2px 8px rgba(0,0,0,0.06)'}}><div className="text-2xl font-extrabold" style={{color:s.c}}>{s.n}</div><div className="text-gray-400 text-sm mt-1">{s.l}</div></div>))}</div>
        <div className="flex items-center gap-3 mb-5"><div className="w-11 h-11 rounded-lg flex items-center justify-center text-white font-black text-sm" style={{background:'#f97316'}}>M1</div><div className="flex-1"><div className="text-gray-900 font-bold text-xl">Soft Launch &mdash; Build the Foundation</div><div className="text-gray-400 text-sm">DFW &middot; Driver-First &middot; Community Seeding &middot; Zero Paid Ads</div></div><div className="text-3xl font-extrabold" style={{color:'#f97316'}}>100K</div></div>
        <Section items={m1} color="#f97316" />
        <div className="flex items-center gap-3 mb-5 mt-12"><div className="w-11 h-11 rounded-lg flex items-center justify-center text-white font-black text-sm" style={{background:'#423DF9'}}>M2</div><div className="flex-1"><div className="text-gray-900 font-bold text-xl">Full Launch &mdash; Growth Ignition</div><div className="text-gray-400 text-sm">All Channels Live &middot; Paid Ads Blitz &middot; Influencers &middot; Geofencing &middot; Press</div></div><div className="text-3xl font-extrabold" style={{color:'#423DF9'}}>400K</div></div>
        <Section items={m2} color="#423DF9" />
        <div className="flex items-center gap-3 mb-5 mt-12"><div className="w-11 h-11 rounded-lg flex items-center justify-center text-white font-black text-sm" style={{background:'#0e7a50'}}>M3</div><div className="flex-1"><div className="text-gray-900 font-bold text-xl">Orbit &mdash; Viral Growth & Retention</div><div className="text-gray-400 text-sm">Referral Compounding &middot; Partnerships &middot; Hackathons &middot; Retention</div></div><div className="text-3xl font-extrabold" style={{color:'#0e7a50'}}>500K</div></div>
        <Section items={m3} color="#0e7a50" />
      </div>
    </div>
  );
}